//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildDisk
    {
        public long TID { get; set; }
        public string BuildID { get; set; }
        public string HDID { get; set; }
    
        public virtual Build Build { get; set; }
        public virtual HardDrive HardDrive { get; set; }
    }
}
