//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build
    {
        public string BuildName { get; set; }
        public string OwnerID { get; set; }
        public string BuildID { get; set; }
        public string PCcase { get; set; }
        public string Motherboard { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string PSU { get; set; }
        public string RAM { get; set; }
        public string Monitor { get; set; }
        public string OpticalDrives { get; set; }
        public string HardDrive { get; set; }
        public string Peripherals { get; set; }
        public string PCIcard { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual CPU CPU1 { get; set; }
        public virtual GPU GPU1 { get; set; }
        public virtual HardDrive HardDrive1 { get; set; }
        public virtual Monitor Monitor1 { get; set; }
        public virtual Motherboard Motherboard1 { get; set; }
        public virtual OpticalDriver OpticalDriver { get; set; }
        public virtual PCICard PCICard1 { get; set; }
        public virtual Peripheral Peripheral { get; set; }
        public virtual PSU PSU1 { get; set; }
        public virtual RAM RAM1 { get; set; }
    }
}
