//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Build()
        {
            this.BuildDisks = new HashSet<BuildDisk>();
            this.BuildMonitors = new HashSet<BuildMonitor>();
            this.BuildODs = new HashSet<BuildOD>();
            this.BuildPCIs = new HashSet<BuildPCI>();
            this.BuildsPeripherals = new HashSet<BuildsPeripheral>();
            this.BuildsRAMs = new HashSet<BuildsRAM>();
        }
    
        public string BuildName { get; set; }
        public string OwnerID { get; set; }
        public string BuildID { get; set; }
        public string CaseID { get; set; }
        public string MBID { get; set; }
        public string CPUID { get; set; }
        public string PSUID { get; set; }
        public string GPUID { get; set; }
        public Nullable<byte> GPUCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildDisk> BuildDisks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildMonitor> BuildMonitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildOD> BuildODs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildPCI> BuildPCIs { get; set; }
        public virtual PCCase PCCase { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual PSU PSU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildsPeripheral> BuildsPeripherals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildsRAM> BuildsRAMs { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
