//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPU()
        {
            this.Builds = new HashSet<Build>();
        }
    
        public string CPUID { get; set; }
        public string ProductID { get; set; }
        public string Cache { get; set; }
        public Nullable<short> Wattage { get; set; }
        public Nullable<bool> Fan { get; set; }
        public Nullable<byte> Threads { get; set; }
        public Nullable<byte> Cores { get; set; }
        public Nullable<byte> MaxRAM { get; set; }
        public Nullable<float> MaxSpeed { get; set; }
        public Nullable<float> Speed { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<float> Stars { get; set; }
        public string Manufacturer { get; set; }
        public string ImageLink { get; set; }
        public string Socket { get; set; }
        public string Chipset { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Build> Builds { get; set; }
    }
}
