//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motherboard()
        {
            this.Builds = new HashSet<Build>();
        }
    
        public string MotherboardID { get; set; }
        public string ProductID { get; set; }
        public string Socket { get; set; }
        public string Chipset { get; set; }
        public Nullable<short> Wattage { get; set; }
        public Nullable<byte> SATASlots { get; set; }
        public Nullable<byte> PCISlots { get; set; }
        public string RAMType { get; set; }
        public Nullable<byte> RAMSlots { get; set; }
        public Nullable<byte> SLILimit { get; set; }
        public Nullable<byte> CrossfireLimit { get; set; }
        public string FormFactor { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public int Price { get; set; }
        public float Stars { get; set; }
        public string Manufacturer { get; set; }
        public string ImageLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Build> Builds { get; set; }
    }
}
