//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAM()
        {
            this.BuildsRAMs = new HashSet<BuildsRAM>();
        }
    
        public string RAMID { get; set; }
        public string product_id { get; set; }
        public Nullable<int> memory_speed { get; set; }
        public Nullable<int> total_capacity { get; set; }
        public string compatibility { get; set; }
        public Nullable<int> voltage { get; set; }
        public Nullable<byte> processor_count { get; set; }
        public Nullable<int> stick_quantity { get; set; }
        public string title { get; set; }
        public string product_description { get; set; }
        public string brand { get; set; }
        public Nullable<int> price { get; set; }
        public string stars { get; set; }
        public byte[] main_image { get; set; }
        public string manufacturer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildsRAM> BuildsRAMs { get; set; }
    }
}
